// AUTO-GENERATED by scripts/gen-promo-timings.mjs — do not edit by hand.
// Scene durations (seconds) + phrase marks (frames, scene-relative) locked to
// the narration take (63.62s total).
export const FPS = 30;
export const NARRATION_SECONDS = 63.62;
export const SCENES = [
  {
    "k": "hook",
    "s": 11.51,
    "marks": {
      "sub": 81,
      "reveal": 287
    }
  },
  {
    "k": "advances",
    "s": 12.62,
    "marks": {
      "chip": 274
    }
  },
  {
    "k": "gst",
    "s": 12.42,
    "marks": {
      "chip": 129
    }
  },
  {
    "k": "ease",
    "s": 7.16,
    "marks": {
      "chip": 113
    }
  },
  {
    "k": "outcome",
    "s": 14.18,
    "marks": {
      "chip": 340
    }
  },
  {
    "k": "cta",
    "s": 5.73,
    "marks": {
      "btn": 35,
      "url": 103
    }
  }
] as const;
export type SceneKey = typeof SCENES[number]['k'];
